name: ((deployment_name))

features:
  use_dns_addresses: true

releases:
- name: kubo-etcd
  version: 2
  url: https://storage.googleapis.com/kubo-public/kubo-etcd-2-ubuntu-trusty-3468.5-20171107-125206-82655546-20171107125213.tgz
  sha1: 044b7a019baae96e97adc7a19da84c64d949a763
- name: kubo
  version: latest
- name: docker
  version: 28.0.1
  url: https://storage.googleapis.com/kubo-public/docker-28.0.1-ubuntu-trusty-3468.5-20171107-125514-444936754-20171107125523.tgz
  sha1: 985e7d430f97cc8a95b539c1bdd04be0d55c10bd
- name: haproxy
  version: 8.4.0
  url: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/download/v8.4.0/haproxy-8.4.0.tgz
  sha1: a3a911f0cf8e672b27c6cb16318fd8c7c77f5bde

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "3468.5"

instance_groups:
- name: master
  instances: 1
  networks:
  - name: &network-name ((deployments_network))
  azs: [z1]
  jobs:
  - name: kubo-dns-aliases
    release: kubo
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: flanneld
    release: kubo
  - name: kubernetes-api
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      backend_port: 8443 # Bosh links hack
      port: ((kubernetes_master_port))
      authorization-mode: &authorization_mode ((authorization_mode))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubeconfig
    release: kubo
    properties:
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubernetes-controller-manager
    release: kubo
    properties: {}
  - name: kubernetes-scheduler
    release: kubo
  - name: kubernetes-system-specs
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      authorization-mode: *authorization_mode
  - name: etcd
    release: kubo-etcd
    properties:
      etcd:
        require_ssl: false
        peer_require_ssl: false
  stemcell: trusty
  vm_type: master

- name: worker
  instances: 3
  networks:
  - name: *network-name
  azs: [z1]
  jobs:
  - name: kubo-dns-aliases
    release: kubo
  - name: flanneld
    release: kubo
  - name: docker
    release: docker
    properties:
      docker:
        flannel: true
        iptables: false
        ip_masq: false
        log_level: error
        storage_driver: overlay
        default_ulimits: [ "nofile=65536" ]
      env: {}
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: "https://((kubernetes_master_host)):((kubernetes_master_port))"
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: kubelet
    release: kubo
    properties:
      tls:
        kubelet: ((tls-kubelet))
  - name: kubernetes-proxy
    release: kubo
  stemcell: trusty
  vm_type: worker
  persistent_disk_type: 10240

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 10000-300000
  update_watch_time: 10000-300000

variables:
- name: kubo-admin-password
  type: password
- name: kubelet-password
  type: password
- name: kube-proxy-password
  type: password
- name: kube-scheduler-password
  type: password
- name: kubo_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: tls-kubelet
  type: certificate
  options:
    ca: kubo_ca
    common_name: kubelet.kubo.internal
    alternative_names: []
    organization: "system:nodes"
- name: tls-kubernetes
  type: certificate
  options:
    ca: kubo_ca
    organization: "system:masters"
    common_name: ((kubernetes_master_host))
    alternative_names:
    - ((kubernetes_master_host))
    - 10.100.200.1
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - master.kubo

# This can be removed once BOSH supports variables in the runtime-config
- name: /dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: /dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth
